# Generated by Django 5.1.7 on 2025-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('store_manager', 'Store Manager')], default='staff', max_length=20),
        ),
    ]
